---
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: solution.py

container:
  image: apluslms/grade-python:math-3.11-4.10-4.10
  mount: exercises/embedded_plot
  cmd: graderutils
