---
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: solution.py

container:
  image: apluslms/grade-python:math-3.9-4.3-4.0
  mount: exercises/embedded_plot
  cmd: graderutils
