---
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: functions.py

container:
  image: apluslms/grade-python:3.11-4.10-4.10
  mount: exercises/hello_python_graderutils
  cmd: graderutils
