---
title: Hello JavaScript!
description: An example of grading JavaScript code with Node.js
instructions: |
    <p>
        In this exercise you must implement a function <code>hello</code>
        that returns a string "<samp>Hello JavaScript!</samp>".
        Please also make your function available for <code>require</code> by adding <code>module.exports = hello</code> at the end of your file.
    </p>
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: functions.js

container:
  image: apluslms/grade-nodejs:11-2.7
  mount: exercises/hello_javascript
  cmd: /exercise/run.sh
