test_groups:
  - module: grader_tests
    description: Grader tests

feedback_template: feedback_plot_png.html

validation:
    display_name: Input validation
    tasks:
        - type: python_import
          file: turtles.py
        - type: python_syntax
          file: turtles.py

